name: atlas-tailor
channels: [conda-forge, pytorch]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - h5py
  - anndata
  - matplotlib
  - pyyaml
  - pytorch
  - pip
  - pip:
      - -e .[test,docs,notebooks]
